[theme]
primaryColor = "#3498db"  # Change to your desired primary color
backgroundColor = "#f5f5f5"  # Change to your desired background color
secondaryBackgroundColor = "#ffffff"  # Change to your desired secondary background color
textColor = "#333333"  # Change to your desired text color
font = "sans-serif"  # Change to your desired font (if available)

[server]
headless = true
enableCORS = false
port = 8501
